### ISSUE TITLE
RPI 3b+ installation

### ISSUE THREAD

**Issue by vegeta340** [boehm-e/spacy-raspberry#1]
Hi All,

i have  a lcd display (hdmi) connected to rpi and it works well with standard raspian but not with this image. Please help with that!

Regards,
Maciej

**Comment by boehm-e** [comment]
Sur it is my fault.
The boot/config.txt is configured to work with dlp lightcrafter picoprojector.
To make it work with regular HDMI display please edit /boot/config.txt and REMOVE these lines (maybe not exact same one):

```
# Added to support DLP2000
dtoverlay=i2c-gpio,i2c_gpio_sda=23,i2c_gpio_scl=24,i2c_gpio_delay_us=2

dtoverlay=dpi18
overscan_left=0
overscan_right=0
overscan_top=0
overscan_bottom=0
framebuffer_width=854
framebuffer_height=480
enable_dpi_lcd=1
display_default_lcd=1
dpi_group=2
dpi_mode=87

dpi_output_format=458773
hdmi_timings=854 0 14 4 12 480 0 2 3 9 0 0 0 60 0
```

**Comment by vegeta340** [comment]
works fine now, thank you very much! :)
