### ISSUE TITLE
Request - en_core_web_lg Data Model

### ISSUE THREAD

**Issue by unkwn1code** [boehm-e/spacy-raspberry#2]
Hey, thanks for the project, I was not amused to find that spaCy didn't want to install on my RPI3.

The only drawback to this image is the small data model - it's ineffective for a project I'm working on. And to top it off I dont know where to begin or I'd try adding the en_core_web_lg model myself.

I would greatly appreciate it!

**Comment by boehm-e** [comment]
In theory, you just have to run
```
python -m spacy download en_core_web_lg
```
Wait a long time, and it should run.
